       IDENTIFICATION DIVISION.
       PROGRAM-ID. COBOLNODEJS.
       ENVIRONMENT DIVISION.
       DATA DIVISION.
       PROCEDURE DIVISION.
       MAIN SECTION.
           DISPLAY "Hello World!".
       MAIN-EXIT.
           STOP RUN.
