       IDENTIFICATION DIVISION.
       PROGRAM-ID. COBOLNODEJS.
       ENVIRONMENT DIVISION.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
           01  FLG-FS.
       PROCEDURE DIVISION.
               DISPLAY "Hello World!".
           EXIT PROGRAM.
