       IDENTIFICATION DIVISION.
       PROGRAM-ID. COBOLNODEJS.
       ENVIRONMENT DIVISION.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
           01 CNT PIC 9(10).
       PROCEDURE DIVISION.
       MAIN SECTION.
           MOVE 0 TO CNT.
           PERFORM UNTIL CNT = 10
               DISPLAY 'HelloWorld!'
               COMPUTE CNT = CNT + 1
           END-PERFORM.
       EXIT-SECTION.
           EXIT PROGRAM.
